services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        NEXT_PUBLIC_CURRENCY: ${NEXT_PUBLIC_CURRENCY}
    ports:
      - "3000:3000"
    # environment:
      # - MONGODB_URI=mongodb://mongo:27017/quickcart
      # - NEXT_PUBLIC_CURRENCY=$
      # Uncomment if building on local
    depends_on:
      - mongo
    volumes:
      # - .:/app
      - /app/node_modules
    env_file:
      - .env.docker

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: